### ISSUE TITLE
Original Loded mod incompatibility

### ISSUE THREAD

**Issue by NerjalNosk** [saturn-volv/Loded-Waypoints#1]
As creator of the mod that first took the name [Loded](https://modrinth.com/mod/loded), I couldn't help but notice when went out a new mod taking the [exact same name](https://modrinth.com/mod/lodestone-waypoints).

While I cannot really blame you for anything, as it is just a word used as a name and I have no rights on it, it may indeed cause confusions when it comes to referencing the mod, hence a name change on your end would most likely help your mod not being shadowed by mine.

However, the real issue comes with the mod IDs. You indeed also took the very same. And while both mods would run just fine together as per their code (despite mine being marked by Modrinth as "server only" because the v3 of the Modrinth API jinxed the "client optional" tag), having the same ID makes it impossible for both mods to be loaded at once, as Fabric would only be screaming at it.

All in all, I hope you can find a more fitting mod name and ID that would allow you to go besides those issues.

**Comment by saturn-volv** [comment]
Thanks so much for getting to me about this! I'll have it changed as soon as I can

Just gotta come up with another suitable name haha

**Comment by NerjalNosk** [comment]
I mean, the one you have as your Modrinth link, "Lodestone Waypoints", would be fairly explicit, and could even drive you towards minimap/worldmap mods compatibility. At least I personally think that one would fit.

**Comment by saturn-volv** [comment]
Went with W.I.T.L (**W**here **I**s **T**hat **L**odestone) as a name, thought that worked. There shouldn't be any compat issues anymore now!
